### PR TITLE
Github Action for Golang unit tests.

### PR DESCRIPTION
**Pull request by jmprusi**

### CODE REVIEW

**Review by guicassolato — DISMISSED** [review]
Screenshot 2021-02-09 at 18 10 29

Now all we need to do is to actually add tests 😆

**Comment by jmprusi** [comment]
> Screenshot 2021-02-09 at 18 10 29
> 
> Now all we need to do is to actually add tests 😆

It is actually running make test.. :) 

image

I guess i should improve that, so it shows "make test" instead of "set -x"

**Comment by guicassolato** [comment]
It looks like some checks moved from "Code Style" to "Test". Is this expected, @jmprusi?

Screenshot 2021-02-09 at 18 26 52

**Comment by jmprusi** [comment]
@guicassolato  honestly, no idea why that is happening...

**Review by guicassolato — APPROVED** [review]

**Pull request merged**
